#!/usr/bin/env ruby

if `which open` != ""
  open = "open"
elsif `which xdg-open` != ""
  open = "xdg-open"
else
  STDERR.puts "open command not found"
  exit
end

# system "#{open} http://pitecan.com/memo.html"
system "#{open} http://GoQuick.org/#{File.basename($0)}"
