#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# % month 2 2017
#

def isleap(y)
  return true if y % 400 == 0
  return false if y % 100 == 0
  return true if y % 4 == 0
  return false
end

def dayofweek(y, m, d) # 0 = Sunday 
  # 1 <= m <= 12, y > 1752 or so
  t = [0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4]
  y -= 1 if m < 3
  (y + y/4 - y/100 + y/400 + t[m-1] + d) % 7
end

days = [
  0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
]

def dayname(y, m, d)
  ['日', '月', '火', '水', '木', '金', '土'][dayofweek(y,m,d)]
end

month = ARGV.shift.to_i
year = ARGV.shift.to_i
days[2] = 29 if isleap(year)

prevyear = year
prevmonth = month - 1
if prevmonth == 0 then
  prevmonth = 12
  prevyear -= 1
end
nextyear = year
nextmonth = month + 1
if nextmonth == 13 then
  nextmonth = 1
  nextyear += 1
end

puts "[予定表 #{prevyear}-#{prevmonth}] [予定表 #{nextyear}-#{nextmonth}]"

(1..days[month]).each { |day|
  puts "#{month}/#{day}(#{dayname(year,month,day)})"
}

puts "[予定表 #{prevyear}-#{prevmonth}] [予定表 #{nextyear}-#{nextmonth}]"

