#!/usr/bin/ruby

require 'digest/md5'
require 'shellwords'

file = ARGV.shift
exit unless file
exit unless File.exist?(file)

ext = ''
if file =~ /^(.*)(\.\w+)$/ then
  ext = $2
end

hash = Digest::MD5.new.update(File.read(file)).to_s

dstfile = "s3://masui.org/#{hash[0]}/#{hash[1]}/#{hash}#{ext}"
system "/usr/local/bin/s3cmd -c /Users/masui/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"
system "echo http://masui.org/#{hash}#{ext}"
system "echo http://masui.org/#{hash}#{ext} | pbcopy"

